/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:/Repos/ryoyaks.github.io/public/6YAbeta1.glb -o 6YAbeta1.new.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/6YAbeta1.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001">
          <primitive object={nodes.Armature} />
        </group>
        <skinnedMesh name="Back_Hair001" geometry={nodes.Back_Hair001.geometry} material={materials['Strawberry_milk_blue.001']} skeleton={nodes.Back_Hair001.skeleton} />
        <group name="Body003">
          <skinnedMesh name="Body002" geometry={nodes.Body002.geometry} material={materials['Manuka_face_blue.001']} skeleton={nodes.Body002.skeleton} />
          <skinnedMesh name="Body002_1" geometry={nodes.Body002_1.geometry} material={materials['Manuka_face_blue.001']} skeleton={nodes.Body002_1.skeleton} />
        </group>
        <group name="Bracelet_L">
          <skinnedMesh name="RETARGETED__Bracelet_L001" geometry={nodes.RETARGETED__Bracelet_L001.geometry} material={materials['metal_1.001']} skeleton={nodes.RETARGETED__Bracelet_L001.skeleton} />
          <skinnedMesh name="RETARGETED__Bracelet_L001_1" geometry={nodes.RETARGETED__Bracelet_L001_1.geometry} material={materials['black.001']} skeleton={nodes.RETARGETED__Bracelet_L001_1.skeleton} />
        </group>
        <group name="Bracelet_R">
          <skinnedMesh name="RETARGETED__Bracelet_R001" geometry={nodes.RETARGETED__Bracelet_R001.geometry} material={materials['black.001']} skeleton={nodes.RETARGETED__Bracelet_R001.skeleton} />
          <skinnedMesh name="RETARGETED__Bracelet_R001_1" geometry={nodes.RETARGETED__Bracelet_R001_1.geometry} material={materials['metal_1.001']} skeleton={nodes.RETARGETED__Bracelet_R001_1.skeleton} />
        </group>
        <skinnedMesh name="Hair002" geometry={nodes.Hair002.geometry} material={materials['flaps_blue.001']} skeleton={nodes.Hair002.skeleton} />
        <skinnedMesh name="Inner" geometry={nodes.Inner.geometry} material={materials['Inner_Black.001']} skeleton={nodes.Inner.skeleton} />
        <skinnedMesh name="Manuka_body002" geometry={nodes.Manuka_body002.geometry} material={materials['Manuka_body.001']} skeleton={nodes.Manuka_body002.skeleton} />
        <skinnedMesh name="Manuka_kemono_ear002" geometry={nodes.Manuka_kemono_ear002.geometry} material={materials['Manuka_hair_blue.001']} skeleton={nodes.Manuka_kemono_ear002.skeleton} />
        <skinnedMesh name="Manuka_kemono_tail002" geometry={nodes.Manuka_kemono_tail002.geometry} material={materials['Manuka_hair_blue.001']} skeleton={nodes.Manuka_kemono_tail002.skeleton} />
        <skinnedMesh name="Pants" geometry={nodes.Pants.geometry} material={materials['Black.001']} skeleton={nodes.Pants.skeleton} />
        <skinnedMesh name="Pants_belt" geometry={nodes.Pants_belt.geometry} material={materials['Black.001']} skeleton={nodes.Pants_belt.skeleton} />
        <group name="Pants_ring">
          <skinnedMesh name="RETARGETED__Pants_ring001" geometry={nodes.RETARGETED__Pants_ring001.geometry} material={materials['Black.001']} skeleton={nodes.RETARGETED__Pants_ring001.skeleton} />
          <skinnedMesh name="RETARGETED__Pants_ring001_1" geometry={nodes.RETARGETED__Pants_ring001_1.geometry} material={materials['metal_1.001']} skeleton={nodes.RETARGETED__Pants_ring001_1.skeleton} />
        </group>
        <skinnedMesh name="Pants_safetypin" geometry={nodes.Pants_safetypin.geometry} material={materials['metal_1.001']} skeleton={nodes.Pants_safetypin.skeleton} />
        <skinnedMesh name="Ribbon001" geometry={nodes.Ribbon001.geometry} material={materials['metal_1.001']} skeleton={nodes.Ribbon001.skeleton} />
        <skinnedMesh name="Shoes" geometry={nodes.Shoes.geometry} material={materials['ACC.001']} skeleton={nodes.Shoes.skeleton} />
        <skinnedMesh name="SR-bang001" geometry={nodes['SR-bang001'].geometry} material={materials['Silent Reverie-ryablue.001']} skeleton={nodes['SR-bang001'].skeleton} />
        <skinnedMesh name="SR-side001" geometry={nodes['SR-side001'].geometry} material={materials['Silent Reverie-ryablue.001']} skeleton={nodes['SR-side001'].skeleton} />
        <skinnedMesh name="Twin_Up001" geometry={nodes.Twin_Up001.geometry} material={materials['Strawberry_milk_blue.001']} skeleton={nodes.Twin_Up001.skeleton} />
        <skinnedMesh name="Twin001" geometry={nodes.Twin001.geometry} material={materials['Strawberry_milk_blue.001']} skeleton={nodes.Twin001.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/6YAbeta1.glb')
