/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/6YAbeta.glb 
*/

import React from 'react'
import * as THREE from 'three'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/6YAbeta.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  

  const { actions, names } = useAnimations(animations, group);
  React.useEffect(() => {
    if (names.length > 0) {
      const action = actions[names[0]];
      

      // action.setLoop(THREE.LoopOnce); // 只播放一次
      // action.clampWhenFinished = true; // 播放完後停在最後一格


      action.reset().fadeIn(0.5).play();
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Armature_2} />
          <group name="Audio" rotation={[Math.PI, 0, Math.PI]} />
          <group name="Hair_set" rotation={[Math.PI, 0, Math.PI]}>
            <group name="flaps" position={[0, -0.2, -0.03]} />
            <group name="Lovely_twin_hair" position={[0, -0.26, 0.012]}>
              <group name="Armature_3" position={[0, 1.54, -0.033]} />
            </group>
            <group name="Silent_Reverie(MANUKA)" position={[0, -0.005, 0]}>
              <group name="Armature_4" />
              <group name="Collider" position={[0, 0.939, 0.018]} />
            </group>
          </group>
          <group name="MANUKA_Logounderwear_breast_small" rotation={[Math.PI, 0, Math.PI]}>
            <group name="Armature001" />
          </group>
          <group name="midnight_color1" rotation={[Math.PI, 0, Math.PI]}>
            <group name="Armature1_3" />
            <group name="AutoAnchorObject" position={[0, 0.591, 0]} />
            <group name="PBarmbadgeL001" />
            <group name="PBarmbadgeL002" />
            <group name="PBarmbadgeL003" />
            <group name="PBarmbadgeR001" />
            <group name="PBarmbadgeR002" />
            <group name="PBarmbadgeR003" />
            <group name="PBarmzipperL" />
            <group name="PBarmzipperR" />
            <group name="PBchestbeltL" />
            <group name="PBchestbeltR" />
            <group name="PBhood" />
            <group name="PBnameplate" />
            <group name="PBneckbelt" />
            <group name="PBouterbeltL" />
            <group name="PBouterbeltLback" />
            <group name="PBouterbeltR" />
            <group name="PBouterbeltRback" />
            <group name="PBpouch" />
            <group name="PBribbon" />
          </group>
          <group name="Obsidian_AM_Variant" rotation={[Math.PI, 0, Math.PI]}>
            <group name="Armature1_2" />
          </group>
          <group name="secondary" rotation={[Math.PI, 0, Math.PI]} />
          <group name="secondary_3" rotation={[Math.PI, 0, Math.PI]} />
          <group name="VRM-secondary" rotation={[Math.PI, 0, Math.PI]} />
          <skinnedMesh name="Hair" geometry={nodes.Hair.geometry} material={materials['N00_000_Hair_00_HAIR (Instance)']} skeleton={nodes.Hair.skeleton} />
          <skinnedMesh name="innerskirt_low" geometry={nodes.innerskirt_low.geometry} material={materials.inner} skeleton={nodes.innerskirt_low.skeleton} />
          <skinnedMesh name="Manuka_LogoUnderwear_shorts_wk" geometry={nodes.Manuka_LogoUnderwear_shorts_wk.geometry} material={materials.Manuka_logounderwear} skeleton={nodes.Manuka_LogoUnderwear_shorts_wk.skeleton} />
          <skinnedMesh name="outerparts_low" geometry={nodes.outerparts_low.geometry} material={materials.outer} skeleton={nodes.outerparts_low.skeleton} />
          <skinnedMesh name="partsarmbadge_low" geometry={nodes.partsarmbadge_low.geometry} material={materials.parts} skeleton={nodes.partsarmbadge_low.skeleton} />
          <skinnedMesh name="partschorker1_low" geometry={nodes.partschorker1_low.geometry} material={materials.parts} skeleton={nodes.partschorker1_low.skeleton} />
          <skinnedMesh name="partschorker2_low" geometry={nodes.partschorker2_low.geometry} material={materials.parts} skeleton={nodes.partschorker2_low.skeleton} />
          <skinnedMesh name="partsgartarbelt_low" geometry={nodes.partsgartarbelt_low.geometry} material={materials.parts} skeleton={nodes.partsgartarbelt_low.skeleton} />
          <skinnedMesh name="partsloafer_low" geometry={nodes.partsloafer_low.geometry} material={materials.parts} skeleton={nodes.partsloafer_low.skeleton} />
          <skinnedMesh name="partspouch_low" geometry={nodes.partspouch_low.geometry} material={materials.parts} skeleton={nodes.partspouch_low.skeleton} />
          <group name="accenameplate1_low">
            <skinnedMesh name="accenameplate1_lowbakedbaked" geometry={nodes.accenameplate1_lowbakedbaked.geometry} material={materials.parts} skeleton={nodes.accenameplate1_lowbakedbaked.skeleton} morphTargetDictionary={nodes.accenameplate1_lowbakedbaked.morphTargetDictionary} morphTargetInfluences={nodes.accenameplate1_lowbakedbaked.morphTargetInfluences} />
            <skinnedMesh name="accenameplate1_lowbakedbaked_1" geometry={nodes.accenameplate1_lowbakedbaked_1.geometry} material={materials.acce} skeleton={nodes.accenameplate1_lowbakedbaked_1.skeleton} morphTargetDictionary={nodes.accenameplate1_lowbakedbaked_1.morphTargetDictionary} morphTargetInfluences={nodes.accenameplate1_lowbakedbaked_1.morphTargetInfluences} />
          </group>
          <skinnedMesh name="Back_Hair" geometry={nodes.Back_Hair.geometry} material={materials['Strawberry milk']} skeleton={nodes.Back_Hair.skeleton} morphTargetDictionary={nodes.Back_Hair.morphTargetDictionary} morphTargetInfluences={nodes.Back_Hair.morphTargetInfluences} />
          <group name="Body">
            <skinnedMesh name="Bodybakedbaked" geometry={nodes.Bodybakedbaked.geometry} material={materials.Manuka_face} skeleton={nodes.Bodybakedbaked.skeleton} morphTargetDictionary={nodes.Bodybakedbaked.morphTargetDictionary} morphTargetInfluences={nodes.Bodybakedbaked.morphTargetInfluences} />
            <skinnedMesh name="Bodybakedbaked_1" geometry={nodes.Bodybakedbaked_1.geometry} material={materials.Manuka_option} skeleton={nodes.Bodybakedbaked_1.skeleton} morphTargetDictionary={nodes.Bodybakedbaked_1.morphTargetDictionary} morphTargetInfluences={nodes.Bodybakedbaked_1.morphTargetInfluences} />
          </group>
          <skinnedMesh name="innerbelt_low" geometry={nodes.innerbelt_low.geometry} material={materials.inner} skeleton={nodes.innerbelt_low.skeleton} morphTargetDictionary={nodes.innerbelt_low.morphTargetDictionary} morphTargetInfluences={nodes.innerbelt_low.morphTargetInfluences} />
          <group name="innersailor_low">
            <skinnedMesh name="innersailor_lowbakedbaked" geometry={nodes.innersailor_lowbakedbaked.geometry} material={materials.inner} skeleton={nodes.innersailor_lowbakedbaked.skeleton} morphTargetDictionary={nodes.innersailor_lowbakedbaked.morphTargetDictionary} morphTargetInfluences={nodes.innersailor_lowbakedbaked.morphTargetInfluences} />
            <skinnedMesh name="innersailor_lowbakedbaked_1" geometry={nodes.innersailor_lowbakedbaked_1.geometry} material={materials.ribbon} skeleton={nodes.innersailor_lowbakedbaked_1.skeleton} morphTargetDictionary={nodes.innersailor_lowbakedbaked_1.morphTargetDictionary} morphTargetInfluences={nodes.innersailor_lowbakedbaked_1.morphTargetInfluences} />
          </group>
          <skinnedMesh name="Manuka_body" geometry={nodes.Manuka_body.geometry} material={materials.Manuka_body} skeleton={nodes.Manuka_body.skeleton} morphTargetDictionary={nodes.Manuka_body.morphTargetDictionary} morphTargetInfluences={nodes.Manuka_body.morphTargetInfluences} />
          <skinnedMesh name="Manuka_kemono_ear" geometry={nodes.Manuka_kemono_ear.geometry} material={materials.Manuka_hair} skeleton={nodes.Manuka_kemono_ear.skeleton} morphTargetDictionary={nodes.Manuka_kemono_ear.morphTargetDictionary} morphTargetInfluences={nodes.Manuka_kemono_ear.morphTargetInfluences} />
          <skinnedMesh name="Manuka_kemono_tail" geometry={nodes.Manuka_kemono_tail.geometry} material={materials.Manuka_hair} skeleton={nodes.Manuka_kemono_tail.skeleton} morphTargetDictionary={nodes.Manuka_kemono_tail.morphTargetDictionary} morphTargetInfluences={nodes.Manuka_kemono_tail.morphTargetInfluences} />
          <skinnedMesh name="Manuka_LogoUnderwear_bra_Breast_small_wk" geometry={nodes.Manuka_LogoUnderwear_bra_Breast_small_wk.geometry} material={materials.Manuka_logounderwear} skeleton={nodes.Manuka_LogoUnderwear_bra_Breast_small_wk.skeleton} morphTargetDictionary={nodes.Manuka_LogoUnderwear_bra_Breast_small_wk.morphTargetDictionary} morphTargetInfluences={nodes.Manuka_LogoUnderwear_bra_Breast_small_wk.morphTargetInfluences} />
          <skinnedMesh name="Obsidian_Earrings" geometry={nodes.Obsidian_Earrings.geometry} material={materials.Mat_UV2_AM} skeleton={nodes.Obsidian_Earrings.skeleton} morphTargetDictionary={nodes.Obsidian_Earrings.morphTargetDictionary} morphTargetInfluences={nodes.Obsidian_Earrings.morphTargetInfluences} />
          <skinnedMesh name="Obsidian_Glasses" geometry={nodes.Obsidian_Glasses.geometry} material={materials.Mat_UV2_AM} skeleton={nodes.Obsidian_Glasses.skeleton} morphTargetDictionary={nodes.Obsidian_Glasses.morphTargetDictionary} morphTargetInfluences={nodes.Obsidian_Glasses.morphTargetInfluences} />
          <skinnedMesh name="Obsidian_Gloves" geometry={nodes.Obsidian_Gloves.geometry} material={materials.Mat_UV3_AM} skeleton={nodes.Obsidian_Gloves.skeleton} morphTargetDictionary={nodes.Obsidian_Gloves.morphTargetDictionary} morphTargetInfluences={nodes.Obsidian_Gloves.morphTargetInfluences} />
          <skinnedMesh name="outerarm_low" geometry={nodes.outerarm_low.geometry} material={materials.outer} skeleton={nodes.outerarm_low.skeleton} morphTargetDictionary={nodes.outerarm_low.morphTargetDictionary} morphTargetInfluences={nodes.outerarm_low.morphTargetInfluences} />
          <skinnedMesh name="outerbody_low" geometry={nodes.outerbody_low.geometry} material={materials.outer} skeleton={nodes.outerbody_low.skeleton} morphTargetDictionary={nodes.outerbody_low.morphTargetDictionary} morphTargetInfluences={nodes.outerbody_low.morphTargetInfluences} />
          <skinnedMesh name="outerinner_low" geometry={nodes.outerinner_low.geometry} material={materials.outer} skeleton={nodes.outerinner_low.skeleton} morphTargetDictionary={nodes.outerinner_low.morphTargetDictionary} morphTargetInfluences={nodes.outerinner_low.morphTargetInfluences} />
          <skinnedMesh name="partsstocking_low" geometry={nodes.partsstocking_low.geometry} material={materials.tights} skeleton={nodes.partsstocking_low.skeleton} morphTargetDictionary={nodes.partsstocking_low.morphTargetDictionary} morphTargetInfluences={nodes.partsstocking_low.morphTargetInfluences} />
          <skinnedMesh name="Ribbon" geometry={nodes.Ribbon.geometry} material={materials['white l']} skeleton={nodes.Ribbon.skeleton} morphTargetDictionary={nodes.Ribbon.morphTargetDictionary} morphTargetInfluences={nodes.Ribbon.morphTargetInfluences} />
          <skinnedMesh name="SR-bang" geometry={nodes['SR-bang'].geometry} material={materials['Silent Reverie-02']} skeleton={nodes['SR-bang'].skeleton} morphTargetDictionary={nodes['SR-bang'].morphTargetDictionary} morphTargetInfluences={nodes['SR-bang'].morphTargetInfluences} />
          <skinnedMesh name="SR-side" geometry={nodes['SR-side'].geometry} material={materials['Silent Reverie-02']} skeleton={nodes['SR-side'].skeleton} morphTargetDictionary={nodes['SR-side'].morphTargetDictionary} morphTargetInfluences={nodes['SR-side'].morphTargetInfluences} />
          <skinnedMesh name="Twin" geometry={nodes.Twin.geometry} material={materials['Strawberry milk']} skeleton={nodes.Twin.skeleton} morphTargetDictionary={nodes.Twin.morphTargetDictionary} morphTargetInfluences={nodes.Twin.morphTargetInfluences} />
          <skinnedMesh name="Twin_Up" geometry={nodes.Twin_Up.geometry} material={materials['Strawberry milk']} skeleton={nodes.Twin_Up.skeleton} morphTargetDictionary={nodes.Twin_Up.morphTargetDictionary} morphTargetInfluences={nodes.Twin_Up.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/6YAbeta.glb')
